### ISSUE TITLE
Markdown block preview shows source 

### ISSUE THREAD

**Issue by ysimonson** [madebymany/sir-trevor-blocks#4]
I'm guessing the preview pane at the top should be showing the compiled markdown results, but it's currently just spitting out the markdown source.

![screen shot 2013-10-22 at 10 23 28 am](https://f.cloud.github.com/assets/127386/1381786/a71ba534-3b25-11e3-9d11-46ab4f7658b2.png)

**Comment by cjbell** [comment]
Actually, this is the expanding textarea representing the results. To make the expanding text area work, with the markdown block you'll need some extra CSS. I based the expanding textarea on this; http://alistapart.com/article/expanding-text-areas-made-elegant
(You'll need to modify the CSS slightly for this to work)

I think what you've highlighted here is a flaw in this blocks repo. Blocks can be made up of JS and CSS so each should probably be their own repos (with tests!).

**Comment by ysimonson** [comment]
Presumably there's some sort of missing library for OrderedList as well, because the latest version does not render a block when you add it
