### ISSUE TITLE
Markdown block render doesn't render correctly

### ISSUE THREAD

**Issue by NicoJuicy** [madebymany/sir-trevor-blocks#5]
The markdown.js render block doesn't seem to render.

I have looked for finding the event (keydown i supposed) in markdown.js, haven't had any results.

Any idea where to look, i'd fix it myself i can find it.

Screenshot:
![image](https://f.cloud.github.com/assets/445937/1391301/06313446-3bfb-11e3-8440-76fe106f2a58.png)

(PS. Great job with sir-trevor)

**Comment by cjbell** [comment]
The markdown block was never intended to preview HTML. The duplicate inputs are for an expanding textarea. See here: https://github.com/madebymany/sir-trevor-blocks/issues/4
